# Generated by Django 4.2.21 on 2025-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='years_of_experience',
            field=models.IntegerField(default=0, verbose_name='years of experience'),
        ),
    ]
