# Generated by Django 4.2 on 2025-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expert_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
    ]
