# Generated by Django 4.2 on 2025-05-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utilisateur_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='country'),
        ),
    ]
