# Generated by Django 4.2 on 2025-06-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_expert_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='country',
        ),
    ]
