# Generated by Django 4.2.21 on 2025-05-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='accounts.expert')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_fr', models.CharField(blank=True, max_length=50, null=True, verbose_name='name (French)')),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description (French)')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description (Arabic)')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'service category',
                'verbose_name_plural': 'service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('document_type', models.CharField(max_length=100, verbose_name='document type')),
                ('processing_time', models.DurationField(verbose_name='processing time')),
                ('requirements', models.TextField(verbose_name='requirements')),
            ],
            options={
                'verbose_name': 'administrative service',
                'verbose_name_plural': 'administrative services',
            },
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='FiscalService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('tax_type', models.CharField(max_length=100, verbose_name='tax type')),
                ('jurisdiction', models.CharField(max_length=100, verbose_name='jurisdiction')),
                ('applicable_law', models.CharField(blank=True, max_length=200, verbose_name='applicable law')),
            ],
            options={
                'verbose_name': 'fiscal service',
                'verbose_name_plural': 'fiscal services',
            },
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='InvestmentService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('investment_type', models.CharField(max_length=100, verbose_name='investment type')),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='minimum investment')),
                ('expected_return', models.CharField(blank=True, max_length=100, verbose_name='expected return')),
                ('risk_level', models.CharField(max_length=50, verbose_name='risk level')),
            ],
            options={
                'verbose_name': 'investment service',
                'verbose_name_plural': 'investment services',
            },
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='RealEstateService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('property_type', models.CharField(max_length=100, verbose_name='property type')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='area (sqm)')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='bedrooms')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='bathrooms')),
            ],
            options={
                'verbose_name': 'real estate service',
                'verbose_name_plural': 'real estate services',
            },
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='TourismService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('includes_transport', models.BooleanField(default=False, verbose_name='includes transport')),
                ('includes_accommodation', models.BooleanField(default=False, verbose_name='includes accommodation')),
                ('includes_meals', models.BooleanField(default=False, verbose_name='includes meals')),
                ('group_size', models.IntegerField(default=1, verbose_name='max group size')),
            ],
            options={
                'verbose_name': 'tourism service',
                'verbose_name_plural': 'tourism services',
            },
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_fr', models.CharField(blank=True, max_length=50, null=True, verbose_name='name (French)')),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description (French)')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description (Arabic)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'service type',
                'verbose_name_plural': 'service types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicetype'),
        ),
    ]
