# Generated by Django 4.2 on 2025-06-24 12:07

from django.db import migrations

def update_categories_to_french(apps, schema_editor):
    """Update service categories to French names"""
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    Service = apps.get_model('services', 'Service')
    
    # Mapping of English to French names
    french_names = {
        'Administrative Services': 'Administratif',
        'Tourism Services': 'Tourisme',
        'Real Estate Services': 'Immobilier', 
        'Fiscal Services': 'Fiscal',
        'Investment Services': 'Investissement'
    }
    
    for category in ServiceCategory.objects.all():
        if category.name in french_names:
            category.name = french_names[category.name]
            category.name_fr = french_names[category.name]
            category.save()
    
    # Activate all services
    Service.objects.all().update(is_active=True)

def reverse_categories_to_english(apps, schema_editor):
    """Reverse migration - update categories back to English"""
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    
    # Mapping of French to English names  
    english_names = {
        'Administratif': 'Administrative Services',
        'Tourisme': 'Tourism Services',
        'Immobilier': 'Real Estate Services',
        'Fiscal': 'Fiscal Services', 
        'Investissement': 'Investment Services'
    }
    
    for category in ServiceCategory.objects.all():
        if category.name in english_names:
            category.name = english_names[category.name]
            category.name_fr = category.name
            category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            update_categories_to_french,
            reverse_categories_to_english
        ),
    ]
