# Generated by Django 4.2 on 2025-07-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_fix_deployment_french_services'),
        ('services', '0002_update_services_to_french'),
    ]

    operations = [
    ]
