# Generated by Django 4.2 on 2025-06-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_requests', '0003_rename_demande_message_service_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('is_responded', models.BooleanField(default=False, verbose_name='is responded')),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
