# Generated by Django 4.2 on 2025-06-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_requests', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='rejection reason'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verified at'),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request_update', 'Request Update'), ('appointment', 'Appointment'), ('appointment_update', 'Appointment Update'), ('message', 'Message'), ('document', 'Document'), ('system', 'System')], max_length=20, verbose_name='notification type'),
        ),
    ]
