# Generated by Django 5.0.2 on 2025-05-28 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Utilisateur'), ('bot', 'Assistant MRE'), ('system', 'Système')], max_length=10)),
                ('content', models.TextField()),
                ('domain_category', models.CharField(blank=True, choices=[('fiscalite', 'Fiscalité'), ('immobilier', 'Immobilier'), ('investissement', 'Investissement'), ('administration', 'Administration'), ('formation', 'Formation professionnelle'), ('other', 'Autre'), ('off_topic', 'Hors sujet')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('api_model_used', models.CharField(default='gemini-2.0-flash-exp', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('fiscalite_questions', models.IntegerField(default=0)),
                ('immobilier_questions', models.IntegerField(default=0)),
                ('investissement_questions', models.IntegerField(default=0)),
                ('administration_questions', models.IntegerField(default=0)),
                ('formation_questions', models.IntegerField(default=0)),
                ('off_topic_questions', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('escalation_rate', models.FloatField(blank=True, null=True)),
                ('satisfaction_avg', models.FloatField(blank=True, null=True)),
                ('signups_from_chat', models.IntegerField(default=0)),
                ('service_requests_from_chat', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='ChatbotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Utile'), ('not_helpful', 'Pas utile'), ('incorrect', 'Incorrect'), ('incomplete', 'Incomplet')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
        ),
    ]
