# Generated by Django 4.2 on 2025-06-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='api_model_used',
            field=models.CharField(default='gpt-4o', max_length=50),
        ),
    ]
