# Generated by Django 4.2 on 2025-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_api_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatanalytics',
            name='failed_responses',
            field=models.IntegerField(default=0),
        ),
    ]
